// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package slurm

/*
#include <slurm/slurm.h>
#include "slurm_helpers.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// SLURM_MAX_NORMAL_STEP_ID as defined in slurm/slurm.h:148
	SLURM_MAX_NORMAL_STEP_ID = (0xfffffff0)
	// SLURM_PENDING_STEP as defined in slurm/slurm.h:150
	SLURM_PENDING_STEP = (0xfffffffd)
	// SLURM_EXTERN_CONT as defined in slurm/slurm.h:152
	SLURM_EXTERN_CONT = (0xfffffffc)
	// SLURM_BATCH_SCRIPT as defined in slurm/slurm.h:154
	SLURM_BATCH_SCRIPT = (0xfffffffb)
	// SLURM_INTERACTIVE_STEP as defined in slurm/slurm.h:156
	SLURM_INTERACTIVE_STEP = (0xfffffffa)
	// SLURM_DIST_STATE_BASE as defined in slurm/slurm.h:830
	SLURM_DIST_STATE_BASE = 0x00FFFF
	// SLURM_DIST_STATE_FLAGS as defined in slurm/slurm.h:831
	SLURM_DIST_STATE_FLAGS = 0xFF0000
	// SLURM_DIST_PACK_NODES as defined in slurm/slurm.h:832
	SLURM_DIST_PACK_NODES = 0x800000
	// SLURM_DIST_NO_PACK_NODES as defined in slurm/slurm.h:833
	SLURM_DIST_NO_PACK_NODES = 0x400000
	// SLURM_DIST_NODEMASK as defined in slurm/slurm.h:835
	SLURM_DIST_NODEMASK = 0xF00F
	// SLURM_DIST_SOCKMASK as defined in slurm/slurm.h:836
	SLURM_DIST_SOCKMASK = 0xF0F0
	// SLURM_DIST_COREMASK as defined in slurm/slurm.h:837
	SLURM_DIST_COREMASK = 0xFF00
	// SLURM_DIST_NODESOCKMASK as defined in slurm/slurm.h:838
	SLURM_DIST_NODESOCKMASK = 0xF0FF
	// SLURM_SSL_SIGNATURE_LENGTH as defined in slurm/slurm.h:982
	SLURM_SSL_SIGNATURE_LENGTH = 128
	// SHOW_ALL as defined in slurm/slurm.h:986
	SHOW_ALL = 0x0001
	// SHOW_DETAIL as defined in slurm/slurm.h:987
	SHOW_DETAIL = 0x0002
	// SHOW_MIXED as defined in slurm/slurm.h:989
	SHOW_MIXED = 0x0008
	// SHOW_LOCAL as defined in slurm/slurm.h:990
	SHOW_LOCAL = 0x0010
	// SHOW_SIBLING as defined in slurm/slurm.h:992
	SHOW_SIBLING = 0x0020
	// SHOW_FEDERATION as defined in slurm/slurm.h:993
	SHOW_FEDERATION = 0x0040
	// SHOW_FUTURE as defined in slurm/slurm.h:995
	SHOW_FUTURE = 0x0080
	// SLURM_POWER_FLAGS_LEVEL as defined in slurm/slurm.h:1503
	SLURM_POWER_FLAGS_LEVEL = 0x0001
	// TRIGGER_FLAG_PERM as defined in slurm/slurm.h:3223
	TRIGGER_FLAG_PERM = 0x0001
	// TRIGGER_RES_TYPE_JOB as defined in slurm/slurm.h:3225
	TRIGGER_RES_TYPE_JOB = 0x0001
	// TRIGGER_RES_TYPE_NODE as defined in slurm/slurm.h:3226
	TRIGGER_RES_TYPE_NODE = 0x0002
	// TRIGGER_RES_TYPE_SLURMCTLD as defined in slurm/slurm.h:3227
	TRIGGER_RES_TYPE_SLURMCTLD = 0x0003
	// TRIGGER_RES_TYPE_SLURMDBD as defined in slurm/slurm.h:3228
	TRIGGER_RES_TYPE_SLURMDBD = 0x0004
	// TRIGGER_RES_TYPE_DATABASE as defined in slurm/slurm.h:3229
	TRIGGER_RES_TYPE_DATABASE = 0x0005
	// TRIGGER_RES_TYPE_FRONT_END as defined in slurm/slurm.h:3230
	TRIGGER_RES_TYPE_FRONT_END = 0x0006
	// TRIGGER_RES_TYPE_OTHER as defined in slurm/slurm.h:3231
	TRIGGER_RES_TYPE_OTHER = 0x0007
	// TRIGGER_TYPE_UP as defined in slurm/slurm.h:3233
	TRIGGER_TYPE_UP = 0x626180
	// TRIGGER_TYPE_DOWN as defined in slurm/slurm.h:3234
	TRIGGER_TYPE_DOWN = 0x626180
	// TRIGGER_TYPE_FAIL as defined in slurm/slurm.h:3235
	TRIGGER_TYPE_FAIL = 0x626180
	// TRIGGER_TYPE_TIME as defined in slurm/slurm.h:3236
	TRIGGER_TYPE_TIME = 0x626180
	// TRIGGER_TYPE_FINI as defined in slurm/slurm.h:3237
	TRIGGER_TYPE_FINI = 0x626180
	// TRIGGER_TYPE_RECONFIG as defined in slurm/slurm.h:3238
	TRIGGER_TYPE_RECONFIG = 0x626180
	// TRIGGER_TYPE_IDLE as defined in slurm/slurm.h:3240
	TRIGGER_TYPE_IDLE = 0x626180
	// TRIGGER_TYPE_DRAINED as defined in slurm/slurm.h:3241
	TRIGGER_TYPE_DRAINED = 0x626180
	// TRIGGER_TYPE_PRI_CTLD_FAIL as defined in slurm/slurm.h:3242
	TRIGGER_TYPE_PRI_CTLD_FAIL = 0x626180
	// TRIGGER_TYPE_PRI_CTLD_RES_OP as defined in slurm/slurm.h:3243
	TRIGGER_TYPE_PRI_CTLD_RES_OP = 0x626180
	// TRIGGER_TYPE_PRI_CTLD_RES_CTRL as defined in slurm/slurm.h:3244
	TRIGGER_TYPE_PRI_CTLD_RES_CTRL = 0x626180
	// TRIGGER_TYPE_PRI_CTLD_ACCT_FULL as defined in slurm/slurm.h:3245
	TRIGGER_TYPE_PRI_CTLD_ACCT_FULL = 0x626180
	// TRIGGER_TYPE_BU_CTLD_FAIL as defined in slurm/slurm.h:3246
	TRIGGER_TYPE_BU_CTLD_FAIL = 0x626180
	// TRIGGER_TYPE_BU_CTLD_RES_OP as defined in slurm/slurm.h:3247
	TRIGGER_TYPE_BU_CTLD_RES_OP = 0x626180
	// TRIGGER_TYPE_BU_CTLD_AS_CTRL as defined in slurm/slurm.h:3248
	TRIGGER_TYPE_BU_CTLD_AS_CTRL = 0x626180
	// TRIGGER_TYPE_PRI_DBD_FAIL as defined in slurm/slurm.h:3249
	TRIGGER_TYPE_PRI_DBD_FAIL = 0x626180
	// TRIGGER_TYPE_PRI_DBD_RES_OP as defined in slurm/slurm.h:3250
	TRIGGER_TYPE_PRI_DBD_RES_OP = 0x626180
	// TRIGGER_TYPE_PRI_DB_FAIL as defined in slurm/slurm.h:3251
	TRIGGER_TYPE_PRI_DB_FAIL = 0x626180
	// TRIGGER_TYPE_PRI_DB_RES_OP as defined in slurm/slurm.h:3252
	TRIGGER_TYPE_PRI_DB_RES_OP = 0x626180
	// TRIGGER_TYPE_BURST_BUFFER as defined in slurm/slurm.h:3253
	TRIGGER_TYPE_BURST_BUFFER = 0x626180
	// TRIGGER_TYPE_DRAINING as defined in slurm/slurm.h:3254
	TRIGGER_TYPE_DRAINING = 0x626180
	// TRIGGER_TYPE_RESUME as defined in slurm/slurm.h:3255
	TRIGGER_TYPE_RESUME = 0x626180
	// SLURM_SUCCESS as defined in slurm/slurm_errno.h:56
	SLURM_SUCCESS = 0
	// SLURM_ERROR as defined in slurm/slurm_errno.h:58
	SLURM_ERROR = -1
	// SLURM_VERSION_NUMBER as defined in slurm/slurm_version.h:41
	SLURM_VERSION_NUMBER = 0x170206
)

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()
